---
- name: Créer un utilisateur Linux
  hosts: ubuntu
  become: true
  gather_facts: true
  tasks:
    - name: Hasher le mot de passe
      ansible.builtin.set_fact:
        hashed_password: "{{ user_password | password_hash('sha512') }}"
      no_log: true
    - name: Créer l'utilisateur
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ hashed_password }}"
        shell: /bin/bash
        create_home: true
        state: present
      no_log: true
    - name: Forcer le changement de mot de passe à la première connexion
      ansible.builtin.command:
        cmd: "chage -d 0 {{ username }}"
      changed_when: true
    - name: Confirmation
      ansible.builtin.debug:
        msg: "Utilisateur '{{ username }}' créé avec succès."
