---
- name: Installer Docker
  hosts: ubuntu
  gather_facts: true
  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes
