---
- name: Installer MariaDB
  hosts: ubuntu
  gather_facts: true
  tasks:
    - name: Installer MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Démarrer MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
