collections:
  - name: https://github.com/ansible-collections/community.mysql.git
    type: git
    version: main
  - name: https://github.com/ansible-collections/community.docker.git
    type: git
    version: main
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
